name = "cm2"# 基础配置
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

# ---------------------------------------------------------
# 环境 1: cm1
# ---------------------------------------------------------
[env.cm1]
name = "cm1"
kv_namespaces = [
  { binding = "KV", id = "b1cd1e9074cd43f989b0ee3b4f913d38" }
]

# ---------------------------------------------------------
# 环境 2: cm2
# ---------------------------------------------------------
[env.cm2]
name = "cm2"
kv_namespaces = [
  { binding = "KV", id = "2502cfe9908a4e40bb24845dd901e10f" }
]

# ---------------------------------------------------------
# 环境 3: cm3
# ---------------------------------------------------------
[env.cm3]
name = "cm3"
kv_namespaces = [
  { binding = "KV", id = "bfe176baecfb4708a6f0ddef0941dca5" }
]

# ---------------------------------------------------------
# 环境 4: cm4
# ---------------------------------------------------------
[env.cm4]
name = "cm4"
kv_namespaces = [
  { binding = "KV", id = "f7081afb04744259bbd4219803f39a44" }
]
